-- $Id: team_renumber.psql,v 1.2 2003/11/19 14:29:02 decibel Exp $

BEGIN TRANSACTION;
SELECT * INTO TEMP team
    FROM temp_new_team_id
    ORDER BY new_id
    LIMIT 10
;

DELETE FROM temp_new_team_id
    WHERE old_id in (SELECT old_id FROM team)
;

UPDATE stats_team
    SET team = n.new_id
    FROM team n
    WHERE stats_team.team in n.old_id
;

INSERT INTO new_team_id(old_id, new_id)
    SELECT old_id, new_id
        FROM team
;
COMMIT;
