COPY CSC_dailies FROM '/home/decibel/blower/CSC_dailies.bcp' WITH DELIMITER '\001';
--COPY CSC_master FROM '/home/decibel/blower/CSC_master.bcp' WITH DELIMITER '\001';
COPY CSC_platform FROM '/home/decibel/blower/CSC_platform.bcp' WITH DELIMITER '\001';
COPY Daily_Summary FROM '/home/decibel/blower/Daily_Summary.bcp' WITH DELIMITER '\001';
--COPY Email_Contrib FROM '/home/decibel/blower/Email_Contrib.bcp' WITH DELIMITER '\001';
COPY Email_Contrib_Last_Update FROM '/home/decibel/blower/Email_Contrib_Last_Update.bcp' WITH DELIMITER '\001' NULL '';
--COPY Email_Rank FROM '/home/decibel/blower/Email_Rank.bcp' WITH DELIMITER '\001';
COPY Email_Rank_Last_Update FROM '/home/decibel/blower/Email_Rank_Last_Update.bcp' WITH DELIMITER '\001' NULL '';
--COPY Platform_Contrib FROM '/home/decibel/blower/Platform_Contrib.bcp' WITH DELIMITER '\001';
COPY Platform_Contrib_Last_Update FROM '/home/decibel/blower/Platform_Contrib_Last_Update.bcp' WITH DELIMITER '\001' NULL '';
COPY Platform_Summary FROM '/home/decibel/blower/Platform_Summary.bcp' WITH DELIMITER '\001';
COPY Project_Status FROM '/home/decibel/blower/Project_Status.bcp' WITH DELIMITER '\001';
COPY Project_statsrun FROM '/home/decibel/blower/Project_statsrun.bcp' WITH DELIMITER '\001' NULL '';
COPY Projects FROM '/home/decibel/blower/Projects.bcp' WITH DELIMITER '\001' NULL '';
--COPY STATS_Participant FROM '/home/decibel/blower/STATS_Participant.bcp' WITH DELIMITER '\001' NULL '';
COPY STATS_Participant_Blocked FROM '/home/decibel/blower/STATS_Participant_Blocked.bcp' WITH DELIMITER '\001';
COPY STATS_Participant_Friend FROM '/home/decibel/blower/STATS_Participant_Friend.bcp' WITH DELIMITER '\001';
COPY STATS_Team_Blocked FROM '/home/decibel/blower/STATS_Team_Blocked.bcp' WITH DELIMITER '\001';
COPY STATS_country FROM '/home/decibel/blower/STATS_country.bcp' WITH DELIMITER '\001';
COPY STATS_cpu FROM '/home/decibel/blower/STATS_cpu.bcp' WITH DELIMITER '\001' NULL '';
COPY STATS_dem_heard FROM '/home/decibel/blower/STATS_dem_heard.bcp' WITH DELIMITER '\001';
COPY STATS_dem_motivation FROM '/home/decibel/blower/STATS_dem_motivation.bcp' WITH DELIMITER '\001';
COPY STATS_nonprofit FROM '/home/decibel/blower/STATS_nonprofit.bcp' WITH DELIMITER '\001';
COPY STATS_os FROM '/home/decibel/blower/STATS_os.bcp' WITH DELIMITER '\001' NULL '';
--COPY STATS_team FROM '/home/decibel/blower/STATS_team.bcp' WITH DELIMITER '\001' NULL '';
--COPY Team_Joins FROM '/home/decibel/blower/Team_Joins.bcp' WITH DELIMITER '\001' NULL '';
--COPY Team_Members FROM '/home/decibel/blower/Team_Members.bcp' WITH DELIMITER '\001';
COPY Team_Members_Last_Update FROM '/home/decibel/blower/Team_Members_Last_Update.bcp' WITH DELIMITER '\001' NULL '';
--COPY Team_Rank FROM '/home/decibel/blower/Team_Rank.bcp' WITH DELIMITER '\001';
COPY Team_Rank_Last_Update FROM '/home/decibel/blower/Team_Rank_Last_Update.bcp' WITH DELIMITER '\001' NULL '';
--COPY csc_CACHE_em_RANK FROM '/home/decibel/blower/statproc.csc_CACHE_em_RANK.bcp' WITH DELIMITER '\001' NULL '';
--COPY csc_CACHE_em_YRANK FROM '/home/decibel/blower/statproc.csc_CACHE_em_YRANK.bcp' WITH DELIMITER '\001' NULL '';
--COPY csc_CACHE_tm_MEMBERS FROM '/home/decibel/blower/statproc.csc_CACHE_tm_MEMBERS.bcp' WITH DELIMITER '\001';
--COPY csc_CACHE_tm_RANK FROM '/home/decibel/blower/statproc.csc_CACHE_tm_RANK.bcp' WITH DELIMITER '\001' NULL '';
--COPY csc_CACHE_tm_YRANK FROM '/home/decibel/blower/statproc.csc_CACHE_tm_YRANK.bcp' WITH DELIMITER '\001' NULL '';
