#!/bin/sh
# $Id: doall,v 1.10 2003/04/14 19:29:36 decibel Exp $

cat ~/blower/Log_Info.bcp |sed -e 's/:000//'>~/blower/Log_Info.bcp.clean||exit 1
touch stats_participant.log email_contrib.log
chmod g+w *.log
chgrp pgsql *.log
sudo -u pgsql ./doall2 | tee doall.log
